// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAleftssKAFR0G0g9osd1a0CLdiLCzAkA',
    appId: '1:219964592239:web:1152860488ca08461b3d9a',
    messagingSenderId: '219964592239',
    projectId: 'moneymaker-admission-dev',
    authDomain: 'moneymaker-admission-dev.firebaseapp.com',
    storageBucket: 'moneymaker-admission-dev.appspot.com',
    measurementId: 'G-1RL4G1KZNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPoezKoIiiTsYARdgAaQ1cq1hRyQDPkCo',
    appId: '1:219964592239:android:c19d3c8db9d8958f1b3d9a',
    messagingSenderId: '219964592239',
    projectId: 'moneymaker-admission-dev',
    storageBucket: 'moneymaker-admission-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO8FIeHqeTGfeclmKPnzTL_fjE3zBqXfQ',
    appId: '1:219964592239:ios:18c955ccdaee59ea1b3d9a',
    messagingSenderId: '219964592239',
    projectId: 'moneymaker-admission-dev',
    storageBucket: 'moneymaker-admission-dev.appspot.com',
    iosBundleId: 'com.example.admissionAppDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO8FIeHqeTGfeclmKPnzTL_fjE3zBqXfQ',
    appId: '1:219964592239:ios:18c955ccdaee59ea1b3d9a',
    messagingSenderId: '219964592239',
    projectId: 'moneymaker-admission-dev',
    storageBucket: 'moneymaker-admission-dev.appspot.com',
    iosBundleId: 'com.example.admissionAppDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAleftssKAFR0G0g9osd1a0CLdiLCzAkA',
    appId: '1:219964592239:web:7f1c1807e508caa41b3d9a',
    messagingSenderId: '219964592239',
    projectId: 'moneymaker-admission-dev',
    authDomain: 'moneymaker-admission-dev.firebaseapp.com',
    storageBucket: 'moneymaker-admission-dev.appspot.com',
    measurementId: 'G-KFFW7FDKBW',
  );
}
